### ISSUE TITLE
Nunca moris :V

### ISSUE THREAD

**Issue by FDSoftware** [FrancisJPK/Juego-en-proceso-activo-waves#1]
![capture](https://cloud.githubusercontent.com/assets/15681280/24962370/2b4c8330-1f72-11e7-9c75-105233f5557f.PNG)
cuando se termina la vida, el juego sigue XD

**Comment by FrancisJPK** [comment]
La posibilidad de perder aun no fue implementada, en la siguiente version habra un sistema de muerte :P

**Comment by FrancisJPK** [comment]
Arreglado :P
