### ISSUE TITLE
Problemas de render :P y de teclado

### ISSUE THREAD

**Issue by FDSoftware** [FrancisJPK/Juego-en-proceso-activo-waves#2]
![k](https://cloud.githubusercontent.com/assets/15681280/24962469/68b4b832-1f72-11e7-9337-bfe5a7383dca.PNG)
si hay muchos objetos, se congela el juego,

aveces conbinar teclas no funciona (ej W y D), y se mueve en una direccion sola

**Comment by FrancisJPK** [comment]
La cantidad de objetos y el problema del teclado se arreglaran en la siguiente version, gracias :D

**Comment by FrancisJPK** [comment]
Solucionado en la update alpha 0.0.2 :P
