### ISSUE TITLE
Se queda en el nivel 1 :V

### ISSUE THREAD

**Issue by FDSoftware** [FrancisJPK/Juego-en-proceso-activo-waves#3]
![capture](https://cloud.githubusercontent.com/assets/15681280/25068649/294705ac-2241-11e7-9ba9-2456b4ae5ad1.PNG)

**Comment by FrancisJPK** [comment]
ah, me olvide de aclarar bien en el update xD ese sistema fue quitado temporalmente :P

**Comment by FrancisJPK** [comment]
arreglado :D
