### ISSUE TITLE
Problemas de colisiones entre objetos

### ISSUE THREAD

**Issue by FDSoftware** [FrancisJPK/Juego-en-proceso-activo-waves#4]
![capture](https://cloud.githubusercontent.com/assets/15681280/25068657/66218baa-2241-11e7-8350-fe5e05983eee.PNG)
luego de un rato de dar vueltas los enemigos amarrilos se fusionan :V, tambien tendrias que hacerlos un poco mas rapidos, son los mas faciles de evitar, cuando la idea es que sea lo contrario XDD

**Comment by FrancisJPK** [comment]
Nope, esto no es un bug xDDD, puse 2 enemigos inteligentes para hacer pruebas, en el juego final no deberia haber mas de uno, llega un momento en el que se fusionan porque estan dirigiendose los 2 al mismo punto , el movimiento del jugador lo unico que hace es retrasar la fusion, o adelantarla, aunque no lo parezca es un triangulo y uno de los angulos es el jugador :PP

**Comment by FrancisJPK** [comment]
en cuanto a la velocidad, va a llegar un momento en el que la dificultad del juego (que aumentara por el puntaje) hara que este enemigo sea muy peligroso, si le pusiese mas velocidad seria injusto. Es probable que cambie su velocidad en funcion del nivel (baja velocidad a mas nivel)
